micronaut:
  http:
    client:
      read-timeout: 600s

btcproxyd:
  rpcproxy:
    network-id: org.bitcoin.production
    uri: http://localhost:8332
    username: setmeplease
    password: setmetooplease
    use-zmq: true
    allow-list:
      - getblockcount
      - getblock
      - getchaintips
      - getbestblockhash
      - getblockchaininfo
      - getblockstats
      - gettxoutsetinfo
      - getaddressinfo
      - getaddressbalance
      - uptime
      - help
      - getrpcinfo
      - getmemoryinfo
      - getnetworkinfo
      - getnettotals
      - getpeerinfo
      - getzmqnotifications
      - listbanned
      - listunspent
      - ping
      - scantxoutset
      - sendrawtransaction
      - omni_listproperties
      - omni_getproperty
      - omni_getallbalancesforaddress
      - omni_getallbalancesforid
      - btcproxy.help
      - btcproxy.proxyinfo
      - omniproxy.help
      - omniproxy.getbalance
      - omniproxy.getbalances
      - omniproxy.getproperty
      - omniproxy.getrichlist
      - omniproxy.listproperties

omniproxyd:
  enabled: true
